# Generated by Django 4.0 on 2024-01-15 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('specialty', models.BooleanField(primary_key=True, serialize=False, verbose_name='specialty')),
                ('meds', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(max_length=100)),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitals',
            },
        ),
        migrations.CreateModel(
            name='Illness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pediatrician',
            fields=[
                ('doctor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.doctor')),
                ('age_limit', models.IntegerField(verbose_name='age limit')),
            ],
            bases=('catalog.doctor',),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.TextField(max_length=30)),
                ('phone', models.TextField(help_text='Enter your phone number', max_length=30)),
                ('condition', models.CharField(max_length=999999999999999999)),
                ('doctor', models.ForeignKey(help_text='Medical doctor', on_delete=django.db.models.deletion.CASCADE, to='catalog.doctor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.hospital')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('disease_effect_time', models.ManyToManyField(related_name='disease_effect_time', to='catalog.Illness')),
                ('diseases', models.ManyToManyField(related_name='diseases', to='catalog.Illness')),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.illness')),
            ],
        ),
    ]
